name:          Przewodnik Dewelopera  @mdo
description:   Standardy tworzenia elastycznego, odpornego i łatwego w utrzymaniu kodu HTML i CSS.
url:           http://codeguide.co

markdown:      rdiscount
permalink:     pretty
pygments:      true
